/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface StatusTag {
        /**
          * @default 'not-started'
         */
        "status": 'completed' | 'in-progress' | 'not-started' | 'cancelled';
        /**
          * @default 'Not started'
         */
        "text": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStatusTagElement extends Components.StatusTag, HTMLStencilElement {
    }
    var HTMLStatusTagElement: {
        prototype: HTMLStatusTagElement;
        new (): HTMLStatusTagElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "status-tag": HTMLStatusTagElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface StatusTag {
        /**
          * @default 'not-started'
         */
        "status"?: 'completed' | 'in-progress' | 'not-started' | 'cancelled';
        /**
          * @default 'Not started'
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "status-tag": StatusTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "status-tag": LocalJSX.StatusTag & JSXBase.HTMLAttributes<HTMLStatusTagElement>;
        }
    }
}
